version: 2.1
jobs:
  static-analysis:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Run ktlint
          command: ./gradlew ktlintCheck
      - run:
          name: Run detekt
          command: ./gradlew detekt

  build-apk:
    parameters:
      target:
        type: string
        description: The target to assemble.
      variant:
        type: string
        description: The variant to assemble.
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "<< parameters.target >>/build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "<< parameters.target >>/build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Run Build APK
          command: ./gradlew :<< parameters.target >>:assemble<< parameters.variant>>

  unit-tests:
    parameters:
      target:
        type: string
        description: The target to test.
      variant:
        type: string
        description: The variant to test.
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "<< parameters.target >>/build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "<< parameters.target >>/build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Run Unit Tests
          command: ./gradlew :<< parameters.target >>:test<< parameters.variant>>UnitTest
      - store_test_results:
          path: << parameters.target >>/build/test-results
      - store_artifacts:
          path: << parameters.target >>/build/reports/tests/testDebugUnitTest
          destination: << parameters.target >>/build/reports/tests/testDebugUnitTest

workflows:
  build-test:
    jobs:
      - static-analysis
      - unit-tests:
          name: unit-tests-stack
          target: app
          variant: StagingDebug
      - unit-tests:
          name: unit-tests-compose-markdown
          target: compose-markdown
          variant: Debug
      - build-apk:
          name: build-apk-stack-debug
          target: app
          variant: Debug
      - build-apk:
          name: build-apk-stack-release
          target: app
          variant: StagingRelease
